### ISSUE TITLE
Support browser polyfill?

### ISSUE THREAD

**Issue by alex-wilmer** [ssorallen/redux-persist-webextension-storage#1]
This seems chrome only at the moment. I could work on this. We have are own lib right now but I wanted to write something compatible with redux persist

**Comment by ssorallen** [comment]
Firefox actually exposes a `chrome` global in its extensions as well and follows the Chrome API https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API: 

> As a porting aid, the Firefox implementation of WebExtensions APIs supports `chrome` and callbacks as well as `browser` and promises.

This could use `browser` as well though and use it with Promises if it exists instead of `chrome`. If you are looking to use this in Firefox, you can already do that.

**Comment by ssorallen** [comment]
Apologies for the slow reply, I didn't realize I wasn't watching this repo. If you want to chat more about this, I will respond more quickly in the future. I'm watching this repo now.

**Comment by ssorallen** [comment]
Implemented by #4.
